#[derive(Debug, PartialEq, Eq, Hash)]
pub enum Button {
    Left,
    Middle,
    Right,
}
#[derive(Debug, PartialEq, Eq, Hash)]
pub enum Action {
    Down,
    Up,
}
#[derive(Debug, PartialEq, Eq, Hash)]
pub enum ScrollAxis {
    Vertical,
    Horizontal,
}
#[derive(Debug, PartialEq, Eq)]
pub enum ApplicationRequest {
    SettingsChange,
    UnsnapMouse,
    SnapMouse,
    Nothing,
    Quit,
}

pub trait InputHandler {
    fn update(&mut self, delta_t: f32, settings: &mut crate::engine::settings::Settings);
    fn handle_key(&mut self, key: Key, action: Action) -> ApplicationRequest;
    fn handle_mouse(&mut self, button: Button, action: Action) -> ApplicationRequest;
    fn handle_wheel(&mut self, axis: ScrollAxis, value: f32);
    fn handle_mouse_move(&mut self, x: i32, y: i32);
    fn settings(&self) -> &super::AppSettings;
}

#[derive(Debug, PartialEq, Eq, Hash)]
pub enum Key {
    None,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    Space,
    Backspace,
    Return,
    Apostrophe,
    Caps,
    Shift,
    CtrlL,
    CtrlR,
    ShiftR,
    KeyUp,
    KeyDown,
    KeyLeft,
    KeyRight,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Zero,
    Minus,
    Equals,
    BracketL,
    BracketR,
    Semicolon,
    Dash,
    Slash,
    Backslash,
    Colon,
    Point,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Esc,
    PrntScr,
    Ins,
    Del,
}

/// Translate a winit [`KeyCode`] to a sparkle game [`Key`].
pub fn translate_key(code: winit::keyboard::KeyCode) -> Key {
    use winit::keyboard::KeyCode::*;
    match code {
        ArrowLeft => Key::KeyLeft,
        ArrowRight => Key::KeyRight,
        ArrowUp => Key::KeyUp,
        ArrowDown => Key::KeyDown,
        Space => Key::Space,
        Backspace => Key::Backspace,
        Enter => Key::Return,
        CapsLock => Key::Caps,
        ShiftLeft => Key::Shift,
        ShiftRight => Key::ShiftR,
        ControlLeft => Key::CtrlL,
        ControlRight => Key::CtrlR,
        Escape => Key::Esc,
        Quote => Key::Apostrophe,
        F1 => Key::F1,
        F2 => Key::F2,
        F3 => Key::F3,
        F4 => Key::F4,
        F5 => Key::F5,
        F6 => Key::F6,
        F7 => Key::F7,
        F8 => Key::F8,
        F9 => Key::F9,
        F10 => Key::F10,
        F11 => Key::F11,
        F12 => Key::F12,
        Digit0 => Key::Zero,
        Digit1 => Key::One,
        Digit2 => Key::Two,
        Digit3 => Key::Three,
        Digit4 => Key::Four,
        Digit5 => Key::Five,
        Digit6 => Key::Six,
        Digit7 => Key::Seven,
        Digit8 => Key::Eight,
        Digit9 => Key::Nine,
        KeyA => Key::A,
        KeyB => Key::B,
        KeyC => Key::C,
        KeyD => Key::D,
        KeyE => Key::E,
        KeyF => Key::F,
        KeyG => Key::G,
        KeyH => Key::H,
        KeyI => Key::I,
        KeyJ => Key::J,
        KeyK => Key::K,
        KeyL => Key::L,
        KeyM => Key::M,
        KeyN => Key::N,
        KeyO => Key::O,
        KeyP => Key::P,
        KeyQ => Key::Q,
        KeyR => Key::R,
        KeyS => Key::S,
        KeyT => Key::T,
        KeyU => Key::U,
        KeyV => Key::V,
        KeyW => Key::W,
        KeyX => Key::X,
        KeyY => Key::Y,
        KeyZ => Key::Z,
        Minus => Key::Minus,
        Equal => Key::Equals,
        BracketLeft => Key::BracketL,
        BracketRight => Key::BracketR,
        Semicolon => Key::Semicolon,
        Slash => Key::Slash,
        Backslash => Key::Backslash,
        Period => Key::Point,
        Insert => Key::Ins,
        Delete => Key::Del,
        PrintScreen => Key::PrntScr,
        _ => Key::None,
    }
}
